### ISSUE TITLE
docs should be without globals as they are deprecated.

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#163] opened 2014-09-16 15:02 UTC

**Comment by SebastianSzturo** [comment] 2015-01-16 08:12
Could someone explain how to use list-view in ember-cli right now?

**Comment by stefanpenner** [comment] 2015-01-17 00:16
@sebastianseilund i'll try to actually addonize it this weekend. It has been extremely overdue.

**Comment by Genkilabs** [comment] 2015-01-19 16:36
Thank you @stefanpenner. The CLI seems to be becoming the norm so making list-view integrate smoothly is greatly appreciated.

**Comment by tim-evans** [comment] 2015-02-10 17:20
This is a duplicate of #153.

**Comment by mrinterweb** [comment] 2015-03-17 19:05
Issue #153 is closed, and the documentation still references globals. I am currently trying to figure out how to fix the deprecation warnings being thrown by the use of globals. So far, I have not had any luck. I'll just live with the deprecation warnings for now.

**Comment by tim-evans** [comment] 2015-03-17 20:48
Mr. @samselikoff is working on the documentation ticket for this. If you'd like a separate ticket for deprecation warnings, we'd definitely welcome that!

**Comment by samselikoff** [comment] 2015-03-17 20:54
yes now that #203 is merged I'm going to go back through and update (after this week's conference)

**Closed** 2017-11-11 13:49 UTC
Labels: Documentation
