### ISSUE TITLE
Is list-view broken on ember 1.13?

### ISSUE THREAD

**Issue by wallaceicy06** [emberjs/list-view#249] opened 2015-07-31 17:45 UTC
Sorry, but I wasn't exactly sure where to ask for help. I tried getting the most basic example of list view working in my ember project, but it doesn't appear to be working. I keep getting an error:

```
Uncaught TypeError: Cannot read property 'helperFunction' of undefined
```

when I insert the following into one of my templates:

```handlebars
{{#ember-list items=model height=500 rowHeight=50 width=500}}
   <p>Hello world!</p>
{{/ember-list}}
```

I've been digging through the issue tracker to see if anyone was having the same issue, and tried using some different handebars helpers but that didn't work. Am I missing something, or is this just broken with the latest version of ember?

**Comment by rwjblue** [comment] 2015-07-31 17:48
Yes, it is broken on 1.13.  This is a duplicate of https://github.com/emberjs/list-view/issues/245 (though this issue is better named :wink: ).

**Comment by stefanpenner** [comment] 2015-07-31 18:50
Let's rename the other one. As it has meow context and ongoing messaging as progress is being made

**Closed** 2015-07-31 18:50 UTC
Labels: Duplicate, Ember Compatability

**Comment by tim-evans** [comment] 2015-07-31 18:54
@stefanpenner done.
