### ISSUE TITLE
rendering via view helper

### ISSUE THREAD

**Issue by xkb** [emberjs/list-view#227] opened 2015-04-06 02:59 UTC
Is today's release suppose to be functional? It's broken :cry: 

I thought it was an issue with my code but then I ran the demo code and it doesn't produce any list items in the DOM.

```
{{#view 'list-view' items=model height=500 rowHeight=50 width=500}}
  {{name}}
{{/view}}
```

~~After some digging around: 
The inner property `items` isn't actually used anywhere(typo?) `list-view-mixin` references data via `content`. With that changed, inner views are created and you can see the scrollbar but there is no content in each view (no {{name}} ).~~

~~Which might be related to the following; in earlier versions if you were extending `list-item-view` data was accessible via a `content` prop but now it seems that's changed to `context.content`?~~

**Comment by stefanpenner** [comment] 2015-04-06 03:01
the following is known to work:

```
<h2 id="title">Welcome to Ember.js</h2>
{{#ember-list height=100  items=model.items width=100 rowHeight=20}}
  <div> hi </div>
{{/ember-list}}
```

**Comment by stefanpenner** [comment] 2015-04-06 03:01
i think the docs are just out of date

**Comment by stefanpenner** [comment] 2015-04-06 03:02
in-fact `item` just becomes `content` https://github.com/emberjs/list-view/blob/master/addon/helper.js#L20

**Comment by KarimBaaba** [comment] 2015-04-06 03:13
Indeed that does work. That's when you're using the `ember-list` helper. 

In the case of using the view helper what needs to be changed here?
```
{{#view 'list-view' content=model height=500 rowHeight=50}}
 <div> hi </div>
{{/view}}
```

**Comment by stefanpenner** [comment] 2015-04-06 03:19
looks like you answered your own question

**Comment by KarimBaaba** [comment] 2015-04-06 03:21
^ No that doesn't work. It creates list of list-item-view but each view is empty.

**Comment by stefanpenner** [comment] 2015-04-06 03:24
> ^ No that doesn't work. It creates list of list-item-view but each view is empty.

ah, that was not clear from your comment.

**Comment by KarimBaaba** [comment] 2015-04-06 03:27
Apologizes. If you have a vague idea of what might be causing this, I can spend some time on it!

**Comment by stefanpenner** [comment] 2015-04-06 03:37
unfortunately I am unable to reproduce issues. Feel free to submit an example app showing your pain point, and i'll be able to look later this week.

**Comment by KarimBaaba** [comment] 2015-04-06 05:48
I created an app showcasing my issue [HERE](https://github.com/KarimBaaba/ember-list-view-bug). There also seems be to an issue with items disappearing when you scroll ( throwing `morph.destroy is not a function` ). Both illustrations included.

Am I doing something wrong here?

**Comment by taras** [comment] 2015-04-06 13:06
You need to upgrade your project to Ember 1.11.1. 1.11.0 has a regression that breaks `ember-list-view`.

**Comment by KarimBaaba** [comment] 2015-04-06 16:50
@taras: Thank you! That fixes the second problem.

Any insight on what's wrong with using the view helper?

**Comment by KarimBaaba** [comment] 2015-04-06 17:44
Back to the first issue.

Doesn't work:
```
 {{view 'list-view' content=model.content height=500 rowHeight=50 width=500}}
```
Works:
```
 {{view 'list-view' content=model.content itemViewClass=viewItem  height=500 rowHeight=50 width=500}}
```

Seems that the itemViewClass must be explicitly passed, is this expected?

**Comment by davidsteinberger** [comment] 2015-04-06 19:56
I'm facing the same issue. Rendering `{{#ember-list ...}} ... {{/ember-list}}` works totally ok. I'd much prefer to work with `{{#view 'list-view' ...}} .. {{/view}}` as it would allow easy subclassing, but in that case the items render blank.

**Comment by maulsea** [comment] 2015-04-09 13:11
FYI, @stefanpenner Your example did work for me.

```
{{#ember-list height=100  items=model.items width=100 rowHeight=20}}
  <div> hi </div>
{{/ember-list}}
```

Just had to remove `.items` from `model.items`. We need to map it directly to model as per model set in docs example.

cc: @KarimBaaba

**Comment by davidsteinberger** [comment] 2015-04-09 13:18
@maulsea The issue is not `#ember-list`. That's known to work just fine. However the new Readme suggests `view 'list-view' ...` but then the items render blank. Does that work for you?
Note: Using the `#collection` helper or providing a *itemViewClass* get the list-view working for me.

**Comment by maulsea** [comment] 2015-04-09 14:21
@davidsteinberger You are right! That does not work. I can't even get it to work with `itemViewClass`.

**Comment by taras** [comment] 2015-04-10 00:44
as @davidsteinberger suggested, using `{{collection}}` renders the list view. I believe reference to `{{view}}` helper in the documentation is incorrect. I submitted a PR to update the documentation and add an acceptance test to make sure that list view renders when using `{{collection}}` helper.

**Comment by KarimBaaba** [comment] 2015-04-10 04:39
@taras: I was aware of this when I opened the issue, I didn't mention it because the collection helper is [deprecate](http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_collection). According to the APIs the view helper should be used to render CollectionView instances as well. Which makes this a bug either with the helper or list-view.

**Comment by taras** [comment] 2015-04-10 11:12
`ember-list` helper uses `collection` helper to render ListView https://github.com/emberjs/list-view/blob/master/addon/helper.js#L32. Until that changes, my guess is that it's safe to use the `{{collection}}` helper.

**Comment by rwjblue** [comment] 2017-11-11 13:46
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...

**Closed by rwjblue** 2017-11-11 13:46 UTC
Labels: Bug, Documentation
